//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class AproTools : global::System.Configuration.ApplicationSettingsBase {
        
        private static AproTools defaultInstance = ((AproTools)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AproTools())));
        
        public static AproTools Default {
            get {
                return defaultInstance;
            }
        }
    }
}
