//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class AproTools : global::System.Configuration.ApplicationSettingsBase {
        
        private static AproTools defaultInstance = ((AproTools)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AproTools())));
        
        public static AproTools Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Adapter_SelectedIndex {
            get {
                return ((string)(this["Adapter_SelectedIndex"]));
            }
            set {
                this["Adapter_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Adapter_IPv4 {
            get {
                return ((string)(this["Adapter_IPv4"]));
            }
            set {
                this["Adapter_IPv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Adapter_Subnet {
            get {
                return ((string)(this["Adapter_Subnet"]));
            }
            set {
                this["Adapter_Subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Adapter_Gateway {
            get {
                return ((string)(this["Adapter_Gateway"]));
            }
            set {
                this["Adapter_Gateway"] = value;
            }
        }
    }
}
